easy_admin:
  site_name: "Morocco <strong>Traveling</strong>"
  design:
    # brand_color: '#1ABC9C'
    menu:
      - { label: "Entities" }
      - label: "Ville"
        icon: "city"
        children:
          - { entity: Ville, label: "listes des villes", icon: "th-list" }
          - { entity: Ville, label: "Ajouter une ville", icon: "plus", params: { action: "new" }}
          # - { entity: Ville, label: "Éditer une ville", icon: "pencil", params: { action: "edit" }}
          # - { entity: Ville, label: "Supprimer une ville", icon: "trash", params: { action: "delete" }}
      
      - label: "Région"
        icon: "map"
        children:
          - { entity: Region, label: "listes des Régions", icon: "th-list" }
          - { entity: Region, label: "Ajouter une Région", icon: "plus", params: { action: "new" }}
          # - { entity: Region, label: "Éditer une Région", icon: "pencil", params: { action: "edit" }}
          # - { entity: Region, label: "Supprimer une Région", icon: "trash", params: { action: "delete" }}

      - label: "Hotel"
        icon: "hotel"
        children:
          - { entity: Hotel, label: "listes des Hotels", icon: "th-list" }
          - { entity: Hotel, label: "Ajouter un Hotel", icon: "plus", params: { action: "new" }}
          # - { entity: Hotel, label: "Éditer un Hotel", icon: "pencil", params: { action: "edit" }}
          # - { entity: Hotel, label: "Supprimer un Hotel", icon: "trash", params: { action: "delete" }}

      - label: "Restaurant"
        icon: "coffee"
        children:
          - { entity: Resto, label: "listes des Restaurants", icon: "th-list" }
          - { entity: Resto, label: "Ajouter un Restaurant", icon: "plus", params: { action: "new" },}
          # - { entity: Resto, label: "Éditer un Restaurant", icon: "pencil", params: { action: "edit" }}
          # - { entity: Resto, label: "Supprimer un Restau", icon: "trash", params: { action: "delete" }}

      - label: "Activité"
        icon: "image"
        children:
          - { entity: Activite, label: "listes des Activités", icon: "th-list" }
          - { entity: Activite, label: "Ajouter une Activité", icon: "plus", params: { action: "new" }}
          # - { entity: Activite, label: "Éditer une Activité", icon: "pencil", params: { action: "edit" }}
          # - { entity: Activite, label: "Supprimer une Activité", icon: "trash", params: { action: "delete" }}
      

      - label: "Camping"
        icon: "caravan"
        children:
          - { entity: Camping, label: "listes des Campings", icon: "th-list" }
          - { entity: Camping, label: "Ajouter un Camping", icon: "plus", params: { action: "new" }}
          # - { entity: Camping, label: "Éditer un Camping", icon: "pencil", params: { action: "edit" }}
          # - { entity: Camping, label: "Supprimer un Camping", icon: "trash", params: { action: "delete" }}
      
      - label: "Marker"
        icon: "map-marker"
        children:
          - { entity: Marker, label: "listes des Marqueurs", icon: "th-list" }
          - { entity: Marker, label: "Ajouter un Marqueur", icon: "plus", params: { action: "new" }}
          # - { entity: Marker, label: "Éditer un Marqueur", icon: "pencil", params: { action: "edit" }}
          # - { entity: Marker, label: "Supprimer un Marqueur", icon: "trash", params: { action: "delete" }}
      
      - label: "Type de voyage"
        icon: "suitcase"
        children:
          - { entity: TypeVoyage, label: "Les types de voyage", icon: "th-list" }
          - { entity: TypeVoyage, label: "Ajouter un type de voyage", icon: "plus", params: { action: "new" }}
          # - { entity: Marker, label: "Éditer un type de voyage", icon: "pencil", params: { action: "edit" }}
          # - { entity: Marker, label: "Supprimer un type de voyage", icon: "trash", params: { action: "delete" }}
      
      - { label: "Sécurité", icon: "lock" }
      - label: "User"
        icon: "user"
        children:
          - { entity: User, label: "listes des Utilisateurs", icon: "th-list" }
          - { entity: User, label: "Ajouter un Utilisateur", icon: "plus", params: { action: "new" }}
          # - { entity: User, label: "Éditer un Utilisateur", icon: "pencil", params: { action: "edit" }}
          # - { entity: User, label: "Supprimer un User", icon: "trash", params: { action: "delete" }}
      - label: "Paramétres"
        icon: "config"


  user:
    display_name: true
    name_property_path: "fullName"

  entities:
    # List the entity class name you want to manage

    Ville:
      class: App\Entity\Ville
      label: "Ville"
      list:
        collapse_actions: true 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        title: "Liste des villes"
        batch_actions: ['show', 'delete']
        filters: ['name']
      form:
        fields:
          - { type: "group", icon: "city", label: "Ville" }
          - name
          - "image"
          - region
          - {property: 'description', type: 'text_editor'}     
      edit:
        title: "Éditer la ville"
        help: "Éditer une ville"
      show:
        help: "Ville"

    Hotel:
      class: App\Entity\Hotel
      label: "Hotel"
      form:
        fields:
          - { type: "group", icon: "hotel", label: "Hotel" }
          - nom
          - ville
          - {property: 'description', type: 'text_editor'}
          - imgPath
      list:
        # collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['nom', 'ville']
        batch_actions: ['show', 'delete']
      edit:
        help: "Éditer un hotel"
      show:
        fields:
          - id
          - nom
          - {property: 'description', type: 'raw'}
          - ville
          - imgPath

    Activite:
      class: App\Entity\Activite
      label: "Activite"
      form:
        fields:
          - { type: "group", icon: "image", label: "Activité" }
          - nom
          - {property: 'description', type: 'text_editor'}
          - ville
          - type
          - imgPath
      edit:
        help: "Éditer une Activité"
      list:
        # collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['nom', 'ville', 'type']
        batch_actions: ['show', 'edit', 'delete']
        fields:
          - nom
          - {property: 'description', type: 'text'}
          - ville
          - type
          - imgPath
      show:
        fields:
          - id
          - nom
          - {property: 'description', type: 'raw'}
          - ville
          - type
          - imgPath

    Resto:
      class: App\Entity\Resto
      label: "Restaurant"
      form:
        fields:
          - { type: "group", icon: "coffee", label: "Restaurant" }
          - nom
          - {property: 'description', type: 'text_editor'}
          - ville
          - imgPath
      edit:
        help: "Éditer un Restaurant"
      list:
        # collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['nom', 'ville']
        batch_actions: ['show', 'edit', 'delete']
        fields:
          - nom
          - description
          - ville
          - imgPath
      show:
        fields:
          - id
          - nom
          - {property: 'description', type: 'raw'}
          - ville
          - imgPath

    User:
      class: App\Entity\User
      label: "user"
      edit:
        help: "Éditer un Utilisateur"
      form:
        fields:
          - { type: "group", icon: "user", label: "<strong>USER</strong>" }
          - nom
          - 'prenom'
          - 'email'
          - 'userName'
          - { property: 'password', type: 'password', type_options: { required: true } }
          # - {property: 'password', type: 'password'}
          - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
      list:
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['userName', 'nom', 'prenom', 'email']
        batch_actions: ['show', 'delete']
        fields:
          - nom
          - 'prenom'
          - 'email'
          - 'userName'
          - roles
      show:
        fields:
          - id
          - nom
          - 'prenom'
          - 'email'
          - 'userName'
          - roles
          
    Camping:
      class: App\Entity\Camping
      label: "camp"
      edit:
        help: "Éditer un campign"
      form:
        fields:
          - { type: "group", icon: "caravan", label: "Activité" }
          - nom
          - {property: 'description', type: 'text_editor'}
          - ville
          - isFree
          - imgPath
      list:
        # collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['nom', 'ville', 'isFree']
        batch_actions: ['show', 'delete']
        fields:
          - nom
          - {property: 'description', type: 'text'}
          - ville
          - isFree
          - imgPath
      show:
        fields:
          - id
          - nom
          - {property: 'description', type: 'raw'}
          - ville
          - isFree
          - imgPath

    Marker:
      class: App\Entity\Marker
      label: "Marker"
      edit:
        help: "Éditer un marqueur"
      form:
        fields:
          - { type: "group", icon: "map-marker", label: "Marqueur" }
          - name
          - lat
          - lng
          - ville
          - {property: 'type', type: 'choice', type_options: { multiple: true, choices: { 'Ville': 'Ville', 'Activité': 'Activité', 'Hotel': 'Hotel', 'Restaurant': 'Restaurant' } } }
          - address
          - {property: 'description', type: 'text-editor'}    
      list:
        collapse_actions: true
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['name', 'ville', 'type']
        batch_actions: ['show', 'delete']
        fields:
          - name
          - lat
          - lng
          - ville
          - type
          - address
          - {property: 'description', type: 'text'}
      show:
        fields:
          - id
          - name
          - lat
          - lng
          - ville
          - type
          - address
          - {property: 'description', type: 'raw'}
          
    Region:
      class: App\Entity\Region
      label: "Region"
      edit:
        help: "Éditer une région"
      form:
        fields:
          - { type: "group", icon: "map", label: "Région" }
          - nom
          - villes
      list:
        # collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['nom']
        batch_actions: ['show', 'delete']
        fields:
          - nom
          - villes
      show:
        fields:
          - id
          - nom
          - villes 
      
    TypeVoyage:
      class: App\Entity\TypeVoyage
      label: "TypeVoyage"
      edit:
        help: "Éditer un type de voyage"
      form:
        fields:
          - { type: "group", icon: "suitcase", label: "type de voyage" }
          - typeVoyage
          - {property: 'description', type: 'text-editor'}
      list:
        collapse_actions: false 
        actions: 
          - {name: 'show', label: 'Afficher' }
          - {name: 'edit', label: 'Editer' }
          - {name: 'delete', label: 'Supprimer' }
        filters: ['typeVoyage']
        batch_actions: ['show', 'delete']
        fields:
          - typeVoyage
          - {property: 'description', type: 'text'}
      show:
        fields:
          - id
          - typeVoyage
          - {property: 'description', type: 'text'}